In [1]:
# !pip install datasets==2.18.0

In [2]:
# !pip install ragas==0.1.9

In [3]:
import pandas as pd

# 设置 Pandas 显示选项
pd.set_option('display.max_columns', None)  # 显示所有列
pd.set_option('display.max_rows', None)     # 显示所有行
pd.set_option('display.width', None)        # 不限制显示宽度
pd.set_option('display.max_colwidth', None)  # 显示所有列，不折叠内容

In [4]:
# from langchain.globals import set_debug

# set_debug(True)

## Context Relevancy

In [9]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import context_relevancy


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['法国的首都是哪里？']*2, 
    'contexts' : [['法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。'], 
    ['法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。该国还以其葡萄酒和精致的美食而闻名。拉斯科（Lascaux）的古代洞穴壁画，里昂的罗马剧院和广阔的凡尔赛宫（Palace of Versailles）证明了其丰富的历史。']],
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)
print(dataset)

# 评估
score = evaluate(dataset, metrics=[context_relevancy])
print(score)

score.to_pandas()

Dataset({
    features: ['question', 'contexts'],
    num_rows: 2
})

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

{'context_relevancy': 0.5000}

,question,contexts,context_relevancy
0,法国的首都是哪里？,[法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。],0.5
1,法国的首都是哪里？,[法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。该国还以其葡萄酒和精致的美食而闻名。拉斯科（Lascaux）的古代洞穴壁画，里昂的罗马剧院和广阔的凡尔赛宫（Palace of Versailles）证明了其丰富的历史。],0.5

In [7]:
data_samples["contexts"][0]

['法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。']

In [8]:
"\n".join(data_samples["contexts"][0])

'法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。'

## Faithfulness

In [10]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import faithfulness


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['爱因斯坦出生于何时何地？']*2,
    'contexts' : [['阿尔伯特·爱因斯坦（生于 1879 年 3 月 14 日）是一位出生于德国的理论物理学家，被广泛认为是有史以来最伟大、最有影响力的科学家之一']]*2,
    'answer': ['爱因斯坦于1879年3月14日出生于德国。', '爱因斯坦于 1879 年 3 月 20 日出生于德国。']
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)
print(dataset)

# 评估
score = evaluate(dataset, metrics=[faithfulness])
print(score)

score.to_pandas()

Dataset({
    features: ['question', 'contexts', 'answer'],
    num_rows: 2
})

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

{'faithfulness': 0.7500}

,question,contexts,answer,faithfulness
0,爱因斯坦出生于何时何地？,[阿尔伯特·爱因斯坦（生于 1879 年 3 月 14 日）是一位出生于德国的理论物理学家，被广泛认为是有史以来最伟大、最有影响力的科学家之一],爱因斯坦于1879年3月14日出生于德国。,1.0
1,爱因斯坦出生于何时何地？,[阿尔伯特·爱因斯坦（生于 1879 年 3 月 14 日）是一位出生于德国的理论物理学家，被广泛认为是有史以来最伟大、最有影响力的科学家之一],爱因斯坦于 1879 年 3 月 20 日出生于德国。,0.5

## Answer Relevance

In [13]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import answer_relevancy


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['法国在哪里，它的首都是什么？']*2,
    'contexts' : [['']]*2,
    'answer': ['法国在西欧。', '法国在西欧，巴黎是其首都。']
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)
print(dataset)

# 评估
score = evaluate(dataset, metrics=[answer_relevancy])
print(score)

score.to_pandas()

Dataset({
    features: ['question', 'contexts', 'answer'],
    num_rows: 2
})

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

{'answer_relevancy': 0.8403}

         question contexts         answer  answer_relevancy
0  法国在哪里，它的首都是什么？       []         法国在西欧。          0.849216
1  法国在哪里，它的首都是什么？       []  法国在西欧，巴黎是其首都。          0.831426

## Context Precision

In [14]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import context_precision


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['法国在哪里，它的首都是什么？']*2,
    'contexts' : [["西欧的法国包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以时其装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名", "该国还以其葡萄酒和精致美食而闻名。拉斯科的古代洞穴壁画、里昂的罗马剧院和广阔的凡尔赛宫证明了其丰富的历史。"],
                 ["该国还以其葡萄酒和精致的美食而闻名。拉斯科的古代洞穴图画，里昂的罗马剧院和", "法国，在西欧，包括中世纪城市，高山村庄和地中海海滩。巴黎是其首都，以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。"]],
    'ground_truth': ['法国位于西欧，首都是巴黎。']*2
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)
print(dataset)

# 评估
score = evaluate(dataset, metrics=[context_precision])
print(score)

score.to_pandas()

Dataset({
    features: ['question', 'contexts', 'ground_truth'],
    num_rows: 2
})

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

Task exception was never retrieved
future: <Task finished name='Task-150' coro=<AsyncClient.aclose() done, defined at D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py:2011> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py", line 2021, in aclose
    await proxy.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_transports\default.py", line 385, in aclose
    await self._pool.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http_proxy.py", line 350, in aclose
    await self._connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_backends\anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\streams\tls.py", line 193, in aclose
    await self.transport_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\_backends\_asyncio.py", line 1261, in aclose
    self._transport.close()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\selector_events.py", line 706, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-151' coro=<AsyncClient.aclose() done, defined at D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py:2011> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py", line 2021, in aclose
    await proxy.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_transports\default.py", line 385, in aclose
    await self._pool.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http_proxy.py", line 350, in aclose
    await self._connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_backends\anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\streams\tls.py", line 193, in aclose
    await self.transport_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\_backends\_asyncio.py", line 1261, in aclose
    self._transport.close()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\selector_events.py", line 706, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-161' coro=<AsyncClient.aclose() done, defined at D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py:2011> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_client.py", line 2021, in aclose
    await proxy.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpx\_transports\default.py", line 385, in aclose
    await self._pool.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http_proxy.py", line 350, in aclose
    await self._connection.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_async\http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\httpcore\_backends\anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\streams\tls.py", line 193, in aclose
    await self.transport_stream.aclose()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\site-packages\anyio\_backends\_asyncio.py", line 1261, in aclose
    self._transport.close()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\selector_events.py", line 706, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Software\anaconda3\envs\py310_LLMAppCourse2\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

{'context_precision': 0.7500}

,question,contexts,ground_truth,context_precision
0,法国在哪里，它的首都是什么？,"[西欧的法国包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名, 该国还以其葡萄酒和精致美食而闻名。拉斯科的古代洞穴壁画、里昂的罗马剧院和广阔的凡尔赛宫证明了其丰富的历史。]",法国位于西欧，首都是巴黎。,1.0
1,法国在哪里，它的首都是什么？,"[该国还以其葡萄酒和精致的美食而闻名。拉斯科的古代洞穴图画，里昂的罗马剧院和, 法国，在西欧，包括中世纪城市，高山村庄和地中海海滩。巴黎是其首都，以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。]",法国位于西欧，首都是巴黎。,0.5

## Context Recall

In [15]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import context_recall


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['法国在哪里，它的首都是什么？']*2,
    'contexts' : [["法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。"],
                 ["法国位于西欧，包括中世纪城市、阿尔卑斯山村庄和地中海海滩。该国还以其葡萄酒和精致的美食而闻名。拉斯科（Lascaux）的古代洞穴壁画，里昂的罗马剧院和广阔的凡尔赛宫（Palace of Versailles）证明了其丰富的历史。"]],
    'ground_truth': ['法国位于西欧，首都是巴黎。']*2
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)
print(dataset)

# 评估
score = evaluate(dataset, metrics=[context_recall])
print(score)

score.to_pandas()

Dataset({
    features: ['question', 'contexts', 'ground_truth'],
    num_rows: 2
})

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

{'context_recall': 1.0000}

,question,contexts,ground_truth,context_recall
0,法国在哪里，它的首都是什么？,[法国位于西欧，包括中世纪城市、高山村庄和地中海海滩。其首都巴黎以其时装屋、包括卢浮宫在内的古典艺术博物馆和埃菲尔铁塔等古迹而闻名。],法国位于西欧，首都是巴黎。,1.0
1,法国在哪里，它的首都是什么？,[法国位于西欧，包括中世纪城市、阿尔卑斯山村庄和地中海海滩。该国还以其葡萄酒和精致的美食而闻名。拉斯科（Lascaux）的古代洞穴壁画，里昂的罗马剧院和广阔的凡尔赛宫（Palace of Versailles）证明了其丰富的历史。],法国位于西欧，首都是巴黎。,1.0